import { MenuItem } from "@/types";

export const menuData: MenuItem[] = [
  {
    id: "item_1",
    name: "Margherita Pizza",
    price: 299,
    category: "Pizza",
    type: "Veg",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400",
    available: true,
    options: [
      { id: "var_1", label: "Small (8\")", price: 299, default: true },
      { id: "var_2", label: "Medium (12\")", price: 449 },
      { id: "var_3", label: "Large (16\")", price: 599 },
    ],
    addons: [
      { id: "addon_1", label: "Extra Cheese", price: 50 },
      { id: "addon_2", label: "Olives", price: 30 },
      { id: "addon_3", label: "Mushrooms", price: 40 },
    ],
  },
  {
    id: "item_2",
    name: "Chicken Tikka Pizza",
    price: 399,
    category: "Pizza",
    type: "Non-Veg",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400",
    available: true,
    options: [
      { id: "var_4", label: "Small (8\")", price: 399, default: true },
      { id: "var_5", label: "Medium (12\")", price: 549 },
      { id: "var_6", label: "Large (16\")", price: 699 },
    ],
    addons: [
      { id: "addon_4", label: "Extra Chicken", price: 80 },
      { id: "addon_5", label: "Jalapeños", price: 25 },
      { id: "addon_6", label: "Extra Cheese", price: 50 },
    ],
  },
  {
    id: "item_3",
    name: "Paneer Butter Masala",
    price: 249,
    category: "Main Course",
    type: "Veg",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400",
    available: true,
    addons: [
      { id: "addon_7", label: "Extra Paneer", price: 60 },
      { id: "addon_8", label: "Naan (2 pcs)", price: 40 },
      { id: "addon_9", label: "Rice", price: 50 },
    ],
  },
  {
    id: "item_4",
    name: "Chicken Biryani",
    price: 299,
    category: "Main Course",
    type: "Non-Veg",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400",
    available: true,
    options: [
      { id: "var_7", label: "Half", price: 299, default: true },
      { id: "var_8", label: "Full", price: 499 },
    ],
    addons: [
      { id: "addon_10", label: "Raita", price: 40 },
      { id: "addon_11", label: "Extra Chicken", price: 100 },
      { id: "addon_12", label: "Boiled Egg", price: 20 },
    ],
  },
  {
    id: "item_5",
    name: "Veg Manchurian",
    price: 179,
    category: "Starters",
    type: "Veg",
    available: true,
    options: [
      { id: "var_9", label: "Dry", price: 179, default: true },
      { id: "var_10", label: "Gravy", price: 199 },
    ],
  },
  {
    id: "item_6",
    name: "Chicken 65",
    price: 249,
    category: "Starters",
    type: "Non-Veg",
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400",
    available: true,
    addons: [
      { id: "addon_13", label: "Extra Spicy", price: 0 },
    ],
  },
  {
    id: "item_7",
    name: "Masala Dosa",
    price: 89,
    category: "South Indian",
    type: "Veg",
    image: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=400",
    available: true,
    addons: [
      { id: "addon_14", label: "Extra Sambar", price: 20 },
      { id: "addon_15", label: "Extra Chutney", price: 15 },
    ],
  },
  {
    id: "item_8",
    name: "Filter Coffee",
    price: 49,
    category: "Beverages",
    type: "Veg",
    available: true,
    options: [
      { id: "var_11", label: "Regular", price: 49, default: true },
      { id: "var_12", label: "Strong", price: 59 },
    ],
  },
  {
    id: "item_9",
    name: "Mango Lassi",
    price: 79,
    category: "Beverages",
    type: "Veg",
    image: "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=400",
    available: true,
  },
  {
    id: "item_10",
    name: "Gulab Jamun",
    price: 69,
    category: "Desserts",
    type: "Veg",
    available: true,
    options: [
      { id: "var_13", label: "2 pcs", price: 69, default: true },
      { id: "var_14", label: "4 pcs", price: 129 },
    ],
  },
  {
    id: "item_11",
    name: "Chicken Shawarma",
    price: 159,
    category: "Wraps",
    type: "Non-Veg",
    available: false, // Currently unavailable
    addons: [
      { id: "addon_16", label: "Extra Mayo", price: 20 },
      { id: "addon_17", label: "Cheese Slice", price: 30 },
    ],
  },
  {
    id: "item_12",
    name: "Paneer Tikka",
    price: 199,
    category: "Starters",
    type: "Veg",
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400",
    available: true,
  },
];